source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ShopMercari' do
  pod 'ReactiveSwift', '~> 1.1'
  pod 'ReactiveCocoa', '~> 5.0.0'
  end

target 'ShopMercariUITests' do
  pod 'ReactiveSwift', '~> 1.1'
  pod 'ReactiveCocoa', '~> 5.0.0'
end

target 'ShopMercariTests' do
  pod 'ReactiveSwift', '~> 1.1'
  pod 'ReactiveCocoa', '~> 5.0.0'
end