platform :ios, '8.0'

target 'MovieSearchEngine' do
  pod 'AFNetworking', '~> 3.0'
  pod 'FBSDKCoreKit', '~> 4.9'
  pod 'MJRefresh', '~> 2.4'
end

target 'MovieSearchEngineTests' do
  pod 'AFNetworking', '~> 3.0'
end