source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'RestaurantSearch' do
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 4.0'
end